-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 17:05:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema decolivre_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `decolivre_bd` ;

-- -----------------------------------------------------
-- Schema decolivre_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decolivre_bd` DEFAULT CHARACTER SET utf8 ;
USE `decolivre_bd` ;

-- -----------------------------------------------------
-- Table `decolivre_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decolivre_bd`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome_usu` VARCHAR(50) NOT NULL,
  `email_usu` VARCHAR(150) NOT NULL,
  `senha_usu` VARCHAR(50) NOT NULL,
  `perfil_usu` VARCHAR(45) NULL COMMENT 'Cliente\nAdministrador\nEmpresa Aerea',
  `situacao_usu` VARCHAR(12) NULL COMMENT 'Ativo\nInativo\nBloqueado\nBanido',
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;

-- insert usuarios
INSERT INTO usuarios (nome_usu, email_usu, senha_usu, perfil_usu, situacao_usu)
VALUES ('Administrador','adm@email.com','202cb962ac59075b964b07152d234b70','Administrador','Ativo');


-- -----------------------------------------------------
-- Table `decolivre_bd`.`passagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decolivre_bd`.`passagens` (
  `id_passagens` INT NOT NULL AUTO_INCREMENT,
  `link_pass` VARCHAR(150) NOT NULL,
  `origem_pass` VARCHAR(50) NOT NULL,
  `destino_pass` VARCHAR(50) NOT NULL,
  `valor_pass` DECIMAL NOT NULL,
  `dt_inicio_pass` DATETIME NULL,
  `dt_fim_pass` DATETIME NULL,
  `internacional_pass` VARCHAR(45) NULL DEFAULT 'Falso' COMMENT 'Nacional - Verdadeiro\nInternacional - Falso',
  `situacao_pass` VARCHAR(15) NULL DEFAULT 'Ativo',
  `fk_usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_passagens`, `fk_usuarios_id_usuarios`),
  INDEX `fk_passagens_usuarios_idx` (`fk_usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_passagens_usuarios`
    FOREIGN KEY (`fk_usuarios_id_usuarios`)
    REFERENCES `decolivre_bd`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decolivre_bd`.`pontos_turisticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decolivre_bd`.`pontos_turisticos` (
  `id_pontur` INT NOT NULL,
  `selecao_pontur` VARCHAR(45) NOT NULL,
  `nome_pontur` VARCHAR(45) NOT NULL,
  `cidade_pontur` VARCHAR(45) NOT NULL,
  `pais_pontur` VARCHAR(45) NULL DEFAULT 'Nacional' COMMENT 'Nacional\nInternacional',
  `imagem1_pontur` VARCHAR(100) NULL,
  `imagem2_pontur` VARCHAR(100) NULL,
  `imagem3_pontur` VARCHAR(100) NULL,
  `fk_usuarios_id_usuarios` INT NOT NULL,
  `fk_passagens_id_passagens` INT NOT NULL,
  `fk_passagens_usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_pontur`, `fk_usuarios_id_usuarios`, `fk_passagens_id_passagens`, `fk_passagens_usuarios_id_usuarios`),
  INDEX `fk_pontos_turisticos_usuarios1_idx` (`fk_usuarios_id_usuarios` ASC),
  INDEX `fk_pontos_turisticos_passagens1_idx` (`fk_passagens_id_passagens` ASC, `fk_passagens_usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_pontos_turisticos_usuarios1`
    FOREIGN KEY (`fk_usuarios_id_usuarios`)
    REFERENCES `decolivre_bd`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pontos_turisticos_passagens1`
    FOREIGN KEY (`fk_passagens_id_passagens` , `fk_passagens_usuarios_id_usuarios`)
    REFERENCES `decolivre_bd`.`passagens` (`id_passagens` , `fk_usuarios_id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decolivre_bd`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decolivre_bd`.`avaliacao` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `avaliacao` INT(5) NULL,
  `curtir_ava` TINYINT NULL,
  `comentario_ava` VARCHAR(150) NULL COMMENT 'Elogio\nCritica\nSugestoes\nPergunta',
  `id_denuncia_ava` INT NULL COMMENT 'id de denuncia da avaliação',
  `situacao_com` VARCHAR(15) NULL DEFAULT 'Inativo' COMMENT 'A situação do comentario pode se: \nAtivo\nInativo\nBloqueado\nExcluido\n\n',
  `fk_usuarios_id_usuarios` INT NOT NULL,
  `fk_pontos_turisticos_id_pontur` INT NOT NULL,
  `fk_pontos_turisticos_usuarios_id_usuarios` INT NOT NULL,
  `avaliacao_id_avaliacao` INT NOT NULL,
  `avaliacao_usuarios_id_usuarios` INT NOT NULL,
  `avaliacao_pontos_turisticos_id_pontur` INT NOT NULL,
  `avaliacao_pontos_turisticos_usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`, `fk_usuarios_id_usuarios`, `fk_pontos_turisticos_id_pontur`, `fk_pontos_turisticos_usuarios_id_usuarios`),
  INDEX `fk_Comentarios_usuarios1_idx` (`fk_usuarios_id_usuarios` ASC),
  INDEX `fk_Comentarios_pontos_turisticos1_idx` (`fk_pontos_turisticos_id_pontur` ASC, `fk_pontos_turisticos_usuarios_id_usuarios` ASC),
  INDEX `fk_avaliacao_avaliacao1_idx` (`avaliacao_id_avaliacao` ASC, `avaliacao_usuarios_id_usuarios` ASC, `avaliacao_pontos_turisticos_id_pontur` ASC, `avaliacao_pontos_turisticos_usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_Comentarios_usuarios1`
    FOREIGN KEY (`fk_usuarios_id_usuarios`)
    REFERENCES `decolivre_bd`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_pontos_turisticos1`
    FOREIGN KEY (`fk_pontos_turisticos_id_pontur` , `fk_pontos_turisticos_usuarios_id_usuarios`)
    REFERENCES `decolivre_bd`.`pontos_turisticos` (`id_pontur` , `fk_usuarios_id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_avaliacao1`
    FOREIGN KEY (`avaliacao_id_avaliacao` , `avaliacao_usuarios_id_usuarios` , `avaliacao_pontos_turisticos_id_pontur` , `avaliacao_pontos_turisticos_usuarios_id_usuarios`)
    REFERENCES `decolivre_bd`.`avaliacao` (`id_avaliacao` , `fk_usuarios_id_usuarios` , `fk_pontos_turisticos_id_pontur` , `fk_pontos_turisticos_usuarios_id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
